-- MySQL Script generated by MySQL Workbench
-- Sat Feb 15 18:15:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestion-biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gestion-biblioteca` ;

-- -----------------------------------------------------
-- Schema gestion-biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion-biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `gestion-biblioteca` ;

-- -----------------------------------------------------
-- Table `gestion-biblioteca`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-biblioteca`.`persona` (
  `id_persona` INT NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `tip_doc` ENUM('DNI', 'CE') NOT NULL,
  `nid` VARCHAR(100) NOT NULL,
  `genero` ENUM('Masculino', 'Femenino') NOT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `fecha_registro` DATE NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `correo_UNIQUE` ON `gestion-biblioteca`.`persona` (`correo` ASC) VISIBLE;

CREATE UNIQUE INDEX `nid_UNIQUE` ON `gestion-biblioteca`.`persona` (`nid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gestion-biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-biblioteca`.`usuario` (
  `id_usuario` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `cod_usuario` VARCHAR(50) NOT NULL,
  `contrasenia` VARCHAR(100) NOT NULL,
  `rol` ENUM('Admin', 'Bibliotecario') NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `gestion-biblioteca`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cod_usuario_UNIQUE` ON `gestion-biblioteca`.`usuario` (`cod_usuario` ASC) VISIBLE;

CREATE INDEX `fk_usuario_persona1_idx` ON `gestion-biblioteca`.`usuario` (`id_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gestion-biblioteca`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-biblioteca`.`autor` (
  `id_autor` INT NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `nacionalidad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-biblioteca`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-biblioteca`.`libro` (
  `id_libro` INT NOT NULL,
  `id_autor` INT NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `anio_publicacion` YEAR NOT NULL,
  `editorial` VARCHAR(100) NOT NULL,
  `isnb` VARCHAR(20) NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  PRIMARY KEY (`id_libro`),
  CONSTRAINT `fk_libro_autor1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `gestion-biblioteca`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `isnb_UNIQUE` ON `gestion-biblioteca`.`libro` (`isnb` ASC) VISIBLE;

CREATE INDEX `fk_libro_autor1_idx` ON `gestion-biblioteca`.`libro` (`id_autor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gestion-biblioteca`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-biblioteca`.`cliente` (
  `id_cliente` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `celular` INT NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_cliente_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `gestion-biblioteca`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_persona1_idx` ON `gestion-biblioteca`.`cliente` (`id_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gestion-biblioteca`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-biblioteca`.`prestamo` (
  `id_prestamo` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_libro` INT NOT NULL,
  `fecha_prestamo` DATE NOT NULL,
  `fecha_devolucion` DATE NULL,
  `estado` ENUM('Prestado', 'Devuelto', 'Atrasado') NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  CONSTRAINT `fk_prestamo_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `gestion-biblioteca`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gestion-biblioteca`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_libro1`
    FOREIGN KEY (`id_libro`)
    REFERENCES `gestion-biblioteca`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_prestamo_cliente_idx` ON `gestion-biblioteca`.`prestamo` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `fk_prestamo_usuario1_idx` ON `gestion-biblioteca`.`prestamo` (`id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_prestamo_libro1_idx` ON `gestion-biblioteca`.`prestamo` (`id_libro` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
